- name: Install Android SDK
  run: |
    sudo apt install -y wget unzip
    mkdir -p $HOME/android-sdk/cmdline-tools
    cd $HOME/android-sdk/cmdline-tools
    wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
    unzip commandlinetools-linux-*.zip
    mv cmdline-tools latest

    yes | latest/bin/sdkmanager --licenses
    latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
